const $=id=>document.getElementById(id);let selected=null;
async function api(url,opt={}){const r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Something went wrong");return d}
function msg(id,t,ok=false){$(id).textContent=t;$(id).style.color=ok?"#17834b":"#c0392b"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
async function candidates(){const list=await api("/api/candidates");$("candidates").innerHTML=list.map(c=>`<div class="candidate" data-id="${c.id}"><b>${esc(c.name)}</b><small>${esc(c.position)} · ${esc(c.className)}</small></div>`).join("");document.querySelectorAll(".candidate").forEach(x=>x.onclick=()=>{if(window.hasVoted)return;document.querySelectorAll(".candidate").forEach(y=>y.classList.remove("selected"));x.classList.add("selected");selected=+x.dataset.id;$("voteBtn").disabled=false})}
async function refresh(){const m=await api("/api/me");if(!m.loggedIn){$("auth").classList.remove("hidden");$("voteArea").classList.add("hidden");return}$("auth").classList.add("hidden");$("voteArea").classList.remove("hidden");$("studentName").textContent=`${m.student.name} (${m.student.studentId})`;window.hasVoted=m.student.hasVoted;$("studentStatus").textContent=m.student.hasVoted?"Vote already recorded":"You have not voted yet";$("voteBtn").disabled=m.student.hasVoted;if(m.student.hasVoted)msg("voteMsg","Your vote has already been recorded.",true);await candidates()}
$("loginForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/login",{method:"POST",body:JSON.stringify({studentId:$("loginStudentId").value,password:$("loginPassword").value})});msg("loginMsg","Login successful.",true);refresh()}catch(x){msg("loginMsg",x.message)}};
$("registerForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/register",{method:"POST",body:JSON.stringify({studentId:$("regStudentId").value,name:$("regName").value,password:$("regPassword").value})});msg("regMsg","Registered. Now login.",true);e.target.reset()}catch(x){msg("regMsg",x.message)}};
$("voteBtn").onclick=async()=>{if(!selected)return;if(!confirm("Submit your vote? You cannot vote again."))return;try{await api("/api/vote",{method:"POST",body:JSON.stringify({candidateId:selected})});msg("voteMsg","Vote recorded successfully.",true);refresh()}catch(x){msg("voteMsg",x.message)}};
$("logout").onclick=async()=>{await api("/api/logout",{method:"POST"});refresh()};
$("adminForm").onsubmit=async e=>{e.preventDefault();try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:$("adminPassword").value})});const d=await api("/api/admin/results");$("results").classList.remove("hidden");$("results").innerHTML=`<p><b>Total votes:</b> ${d.totalVotes} / ${d.totalStudents}</p>`+d.results.map((r,i)=>`<div class="result"><span>${i+1}. ${esc(r.name)}</span><b>${r.votes}</b></div>`).join("")}catch(x){$("results").classList.remove("hidden");$("results").textContent=x.message}};refresh();